id: P005645
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4337
  title: འདས་ལོག་དཀར་ཆག་ཐར་པའི་མེ་ལོང་ལམ་སྟོན་གསལ་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    de6e207e886546818a260c05476cd2ba:
      image_group_id: I3CN4584
      title: ''
      volume_number: 1
      total_pages: 158
